# Uncomment the next line to define a global platform for your project
platform :tvos, '9.0'

target 'sample_integration' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sample_integration
  pod 'EmbraceIO-EAP', :git => 'https://github.com/embrace-io/embrace-ios-eap.git', :branch => 'tvos_support'
end
