source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'

target 'sample_integration' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sample_integration
  pod 'EmbraceIO'
end
